### ISSUE TITLE
withFlag should be most general

### ISSUE THREAD

**Issue by rqbazan** [riqra/feature-flags#7]
### Description

Currently `withFlag` HOC constrains to wrapped component with only one feature name. Let see some code:

```js
import { withFlag } from '@riqra/feature-flags'
import { OneComponent } from 'wherever'

const OneComponentWithFlag = withFlag('my-feature')(OneComponent)

...

<OneComponentWithFlag oneProp={whatever}>
	...
</OneComponentWithFlag>

```

Now, to use `OneComponent` with another feature flag, for example: `'my-new-feature'` we need re-create `OneComponent` or do the following:

```js
//one-component-with-flag.js
import { withFlag } from '@riqra/feature-flags'
import OneComponent from 'wherever'

export default ({ flag, ...rest }) => {
  return withFlag(flag)(<OneComponent {...rest} />)
}

//another-component.js
import { OneComponentWithFlag } from './one-component-with-flag.js'

<OneComponentWithFlag flag='my-feature' oneProp={whatever}>
	...
</OneComponentWithFlag>

<OneComponentWithFlag flag='my-new-feature' oneProp={whatever}>
	...
</OneComponentWithFlag>
```

And theoretically now `withFlag` it's unnecessary 🤔 since I can do:

```js
//one-component-with-flag.js
import { Flag } from '@riqra/feature-flags'
import OneComponent from 'wherever'

export default ({ flag, ...rest }) => {
  return (
	<Flag flag={flag}>
		<OneComponent {...rest} />
	</Flag>
  )
}
``` 

### Proposal

`withFlag` should be most general, I mean it should support the following:

```js
import { withFlag } from '@riqra/feature-flags'
import OneComponent from 'wherever'

const OneComponentWithFlag = withFlag(OneComponent)

<OneComponentWithFlag flag='my-feature' oneProp={whatever}>
	...
</OneComponentWithFlag>

<OneComponentWithFlag flag='my-new-feature' oneProp={whatever}>
	...
</OneComponentWithFlag>
```

### Links / references

None

**Comment by klujanrosas** [comment]
I don't think this responsibility should be in the hands of `withFlag`, if you remove the `slug` argument from the HoC it defeats it's purpose, as it shouldn't even be called withFlag anymore, just a plain utility that uses Flag should suffice for your needs.

What I propose instead, is that if you pass a `flag` prop to the wrapped component, we should override the initial slug argument, giving you the necessary flexibility to decide when you want it to behave that way or not. 

:tada:

**Comment by rqbazan** [comment]
Well, then I think the purpose of `withFlag` is incorrect 'cause it constrains to wrapped component with only one feature name and this behaviour limit the React capacity to reuse a component. 🔥

**Comment by klujanrosas** [comment]
Closing this now.
